### ISSUE TITLE
添加更多的编译参数以对路由器(mt7621)的支持

### ISSUE THREAD

**Issue by sleep1223** [cyp0633/drcom-go#1]
.github/workflows/build.yml

```yaml
          - goos: linux
            goarch: mips
          - goos: linux
            goarch: mipsle
            gomips: softfloat # mt7621
```

```yaml
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOMIPS: ${{ matrix.gomips}}
```

完整文件链接: [workflows/build.yml](https://github.com/sleep1223/drcom-go/blob/master/.github/workflows/build.yml)

```yaml
name: Build

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - master
    paths:
      - "**/*.go"
      - "**/*.mod"
      - "**/*.sum"
      - "**/*.yml"
  pull_request:
    branches:
      - master
    paths:
      - "**/*.go"
      - "**/*.mod"
      - "**/*.sum"
      - "**/*.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        goos: [windows, freebsd, openbsd, linux, dragonfly, darwin]
        goarch: [amd64, 386]
        exclude:
          - goarch: 386
            goos: darwin
          - goarch: 386
            goos: dragonfly
        include:
          - goos: darwin
            goarch: arm64
          - goos: windows
            goarch: arm64
          - goos: linux
            goarch: riscv64
          - goos: linux
            goarch: arm64
          - goos: linux
            goarch: loong64
          - goos: linux
            goarch: mips
          - goos: linux
            goarch: mipsle
            gomips: softfloat # mt7621
          - goos: linux
            goarch: mips64
          - goos: linux 
            goarch: mips64le
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOMIPS: ${{ matrix.gomips}}
      GO111MODULE: on
      CGO_ENABLED: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.1
          check-latest: true
      - name: Build
        run: go build -o bin/${{ matrix.goos }}_${{ matrix.goarch }}/main
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.goos }}_${{ matrix.goarch }}
          path: bin/${{ matrix.goos }}_${{ matrix.goarch }}/main
          retention-days: 1

```
